backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
future: true

media_folder: 'assets/images/uploads'

collections:

  - name: 'commentaries-blog'
    label: 'Commentaries Blog'
    folder: '_posts/commentaries'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          multiple: true,
          displayFields: [name],
          searchFields: [name],
          valueField: 'display_name',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Category', name: 'category', widget: 'hidden', default: 'commentaries' }

  - name: 'epidemic-models-blog'
    label: 'Epidemic Models Blog'
    folder: '_posts/epidemic-models'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          multiple: true,
          displayFields: [name],
          searchFields: [name],
          valueField: 'display_name',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Category', name: 'category', widget: 'hidden', default: 'epidemic-models' }

  - name: 'health-management-blog'
    label: 'Health Management Blog'
    folder: '_posts/health-management'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          multiple: true,
          displayFields: [name],
          searchFields: [name],
          valueField: 'display_name',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Category', name: 'category', widget: 'hidden', default: 'health-management' }

  - name: 'articles-blog'
    label: 'Articles Blog'
    folder: '_posts/articles'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          multiple: true,
          displayFields: [name],
          searchFields: [name],
          valueField: 'display_name',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Category', name: 'category', widget: 'hidden', default: 'articles' }

  - name: 'events'
    label: 'Events'
    folder: '_events/'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Event Date', name: 'event_date', widget: 'datetime' }
      - { label: 'Event Organizer', name: 'event_organizer', widget: 'string', required: false }
      - { label: 'Event Timezone', name: 'event_timezone', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Category', name: 'category', widget: 'hidden', default: 'events' }

  - name: 'authors'
    label: 'Authors'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Id', name: 'ids', widget: 'number' }
      - { label: 'Full Name', name: 'name', widget: 'string' }
      - { label: 'Short Name', name: 'display_name', widget: 'string' }
      - { label: 'Role', name: 'role', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string', required: false }
      - { label: 'Website', name: 'website', widget: 'string', required: false }
      - { label: 'Github', name: 'github', widget: 'string', required: false }
      - { label: 'Linkedin', name: 'linkedin', widget: 'string', required: false }
      - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
      - { label: 'Photo Src', name: 'photo_src', widget: 'string' }
      - { label: 'Bio', name: 'description', widget: 'markdown', required: false }

  - name: "page"
    label: "Pages"
    folder: "_pages"
    create: true
    slug: ".md"
    fields:
      - { label: 'Layout', name: 'layout', widget: 'string', default: 'default' }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false }

  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation Items"
            name: "main"
            widget: "list"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Url, name: url, widget: string}
              - {label: Icon, name: icon, widget: string}
              - label: "Navigation Children"
                name: "children"
                widget: "list"
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Url, name: url, widget: string}
                  - {label: Icon, name: icon, widget: string}
